### ISSUE TITLE
Include time tree

### ISSUE THREAD

**Issue by trvrb** [blab/nextflu#59]
Just had a discussion with @rambaut. He pointed out that the recent dominance of 3C.2a would be obvious in a time-stamped tree. In this case, 3C.2a would be "ahead" of 3C.3a. We could imagine having inferred dates of ancestral nodes and then a toggle in auspice to stretch/shrink x-values between substitutions and time.

Not sure how best to do this however. A simple regression of tip date vs substitutions works well to get the overall rate of substitution ([Path-O-Gen](http://tree.bio.ed.ac.uk/software/pathogen/) style), but I'm not sure this would work well to rescale the subs tree into a time tree.

Simplest solution might be to just add a coloring option that displays time...

**Comment by rneher** [comment]
it wouldn't solve the issue completely, since the competing clade is typically still alive. the date slider allows you to do this, right. if leaves only get pruned from one clade, that is the only clade that is growing. when multiple clades have recent leaves, you need to see the frequency dynamics. 

date coloring is easy. we can simply use num_date and map it to color. (flu.tuebingen.mpg.de has this feature). I think some delta frequency would be good.

**Comment by trvrb** [comment]
I'd still like to try to annotate internal nodes with estimated dates at some point. This could be visualized a couple different ways, but I do still like the idea of trying to do the x-axis proportional to time and draw a axis below the tree.

No hurry with this however.

**Comment by rneher** [comment]
I have challenged my people to build a simply python based tool to turn an exisiting topology into a time tree. should be pretty straight-forward and could be included into the pipeline

**Comment by trvrb** [comment]
This is slated for inclusion in augur v2. It won't be included here.
